name: Build and Push to Public ECR

on:
  push:
    branches: [ "main" ]
    tags:
      - 'v*'

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: ${{ vars.AWS_REGION }}
  ECR_ALIAS: ${{ vars.ECR_ALIAS }}
  ECR_REPO: ${{ vars.ECR_REPO }}
  IMAGE_NAME: ${{ vars.IMAGE_NAME }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Login to Public ECR
        run: |
          aws ecr-public get-login-password --region ${{ vars.AWS_REGION }} \
            | docker login --username AWS --password-stdin public.ecr.aws

      - name: Build image
        run: |
          docker build -t ${{ vars.IMAGE_NAME }}:${{ github.sha }} .

      - name: Tag Docker image
        run: |
          # Tag as latest if on main branch
          if [[ "${GITHUB_REF}" == "refs/heads/main" ]]; then
            docker tag $IMAGE_NAME:${GITHUB_SHA} public.ecr.aws/$ECR_ALIAS/$ECR_REPO:latest
          fi
          # Tag with version if pushed via tag
          if [[ "${GITHUB_REF}" == refs/tags/* ]]; then
            TAG_NAME=${GITHUB_REF#refs/tags/}
            docker tag $IMAGE_NAME:${GITHUB_SHA} public.ecr.aws/$ECR_ALIAS/$ECR_REPO:$TAG_NAME
          fi


      - name: Push Docker image
        run: |
          # Push latest if exists
          if [[ "${GITHUB_REF}" == "refs/heads/main" ]]; then
            docker push public.ecr.aws/$ECR_ALIAS/$ECR_REPO:latest
          fi
          # Push version tag if exists
          if [[ "${GITHUB_REF}" == refs/tags/* ]]; then
            TAG_NAME=${GITHUB_REF#refs/tags/}
            docker push public.ecr.aws/$ECR_ALIAS/$ECR_REPO:$TAG_NAME
          fi